MKFILE:=-C .. -f makefile

release:
	make release $(MKFILE)

debug:
	make debug $(MKFILE)

run:
	make run $(MKFILE)

run2:
	make run2 $(MKFILE)

debugrun:
	make debugrun $(MKFILE)

valgrind:
	make valgrind $(MKFILE)

install:
	make install $(MKFILE)

clean:
	make clean $(MKFILE)

test:
	make test $(MKFILE)
