release:
	make release -C ..

debug:
	make debug -C ..

run:
	make run -C ..

debugrun:
	make debugrun -C ..

valgrind:
	make valgrind -C ..

clean:
	make clean -C ..

test:
	make test -C ..
